My webpage version 1.0
AlexHenkel/WebDevExercises pull request #1
Opened 2018-05-05 04:56 UTC by ricglz0201

I create my webpage using html, css and bootstrap.

2018-05-05 17:06 UTC, AlexHenkel commented
Congratulations! It's a great start. But, what about including Bootstrap in your project? I think it will improve a lot your design in order to be responsive out of the box

2018-05-06 00:33 UTC, ricglz0201 commented
Oh! I thought I had included it, I will add it.

2018-05-06 01:30 UTC, AlexHenkel requested changes

2018-05-06 01:30 UTC, AlexHenkel commented on Exercise-HTML-CSS-1/RicardoGlz/Excersise1.html
> +                    <form>
You should only use one `<form>` tag that wraps all your inputs, selects or any other components of the form plus the submit button.

2018-05-06 01:30 UTC, AlexHenkel commented on Exercise-HTML-CSS-1/RicardoGlz/Excersise1.html
> +                <div class="Title-Location">
Please use only lower case to name clases (Ex. `title-location`). Also try to always use English to name classes and id's

2018-05-06 01:30 UTC, AlexHenkel commented on Exercise-HTML-CSS-1/RicardoGlz/Excersise1.html
> +                <div class="Wrapper">
In this exercise, it's required to use Bootstrap's grid system

2020-04-26 13:20 UTC, closed without merging